spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB


  h2:
    console:
      enabled: true
  datasource:
    driver-class: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
